//
// Created by Diaz, Diego on 17.10.2022.
//
#include<iostream>
#include<bwt_io.h>
#include<file_streams.hpp>

int main(int argc, char** argv) {

    if (argc != 3) {
        std::cout << "usage: ./grl2plain file.rlbwt output_file\n\n"
                     "file.rlbwt: the BCR BWT file generated by grlBWT\n"
                     "output_file: output file where the plain BWT fill be stored" << std::endl;
        exit(0);
    }

    errno = 0;
    std::string input_file = std::string(argv[1]);
    std::string output_file = std::string(argv[2]);

    o_file_stream<uint8_t> plain_bwt(output_file, 1024*1024, std::ios::out);

    bwt_buff_reader bwt_reader(input_file);
    size_t sym=0, len=0;
    for(size_t i=0;i<bwt_reader.size();i++) {
        bwt_reader.read_run(i, sym, len);
        for(size_t j=0;j<len;j++){
            plain_bwt.push_back((char)sym);
        }
    }
    plain_bwt.close();
    bwt_reader.close();
}
