//
// Created by Diaz, Diego on 17.10.2022.
//
#include<iostream>
#include<bwt_io.h>
#include<file_streams.hpp>

int main(int argc, char** argv) {

    if (argc<3 || argc>5) {
        std::cout << "usage: ./grl2plain file.rlbwt output_file rep_null\n\n"
                     "file.rlbwt: the BCR BWT file generated by grlBWT\n"
                     "output_file: output file where the plain BWT fill be stored\n"
                     "rep_null: character to which replace the null character (by default is not replaced)" << std::endl;
        exit(0);
    }

    errno = 0;
    uint8_t null_char = 0;

    std::string input_file = std::string(argv[1]);
    std::string output_file = std::string(argv[2]);
    o_file_stream<uint8_t> plain_bwt(output_file, 1024*1024, std::ios::out);
    bwt_buff_reader bwt_reader(input_file);
    size_t sym=0, len=0;

    if(argc==4){
        char *endptr;
        long nchar = strtol(argv[3], &endptr, 10);
        assert(nchar<256);
        null_char = (uint8_t)nchar;

        std::cout<<" The null character will be replaced with "<<(int)null_char<<std::endl;
        for(size_t i=0;i<bwt_reader.size();i++) {
            bwt_reader.read_run(i, sym, len);
            if(sym==0) sym = null_char;
            for(size_t j=0;j<len;j++){
                plain_bwt.push_back((char)sym);
            }
        }
    }else{
        for(size_t i=0;i<bwt_reader.size();i++) {
            bwt_reader.read_run(i, sym, len);
            for(size_t j=0;j<len;j++){
                plain_bwt.push_back((char)sym);
            }
        }
    }

    plain_bwt.close();
    bwt_reader.close();
}
