//
// Created by Diaz, Diego on 14.9.2022.
//
#include<iostream>
#include<bwt_io.h>
#include<file_streams.hpp>

int main(int argc, char** argv) {

    if (argc != 5) {
        std::cout << "usage: ./reverse_bwt file.rlbwt output_prefix\n\n"
                     "file.rlbwt: the BCR BWT file generated by grlBWT\n"
                     "output_prefix: output prefix for the RLE files" << std::endl;
        exit(0);
    }

    errno = 0;
    std::string input_file = std::string(argv[1]);
    std::string output_prefix = std::string(argv[2]);

    o_file_stream<uint32_t> r_lens(output_prefix+".len", 1024*1024, std::ios::out);
    o_file_stream<uint8_t> r_syms(output_prefix+".syms", 1024*1024, std::ios::out);

    bwt_buff_reader bwt_reader(input_file);
    size_t sym=0, len=0;
    for(size_t i=0;i<bwt_reader.size();i++) {
        bwt_reader.read_run(i, sym, len);
        r_syms.push_back(sym);
        r_lens.push_back(len);
    }
    r_lens.close();
    r_syms.close();
    bwt_reader.close();
}