#include <iostream>
#include "fm_index.h"
#include "file_streams.hpp"

int main(int argc, char** argv){

    if(argc!=4){
        std::cout<<"usage: ./reverse_bwt file.rlbwt n_seqs output_file\n\n"
                   "file:   the BCR BWT file generated by grlBWT\n"
                   "n_seqs: the first n_seq sequences of the original file will be decompressed\n"
                   "output_file: file where the sequences will decompressed"<<std::endl;
        exit(0);
    }

    errno = 0;
    char *endptr;
    long n_seqs = strtol(argv[2], &endptr, 10);

    std::string input_file = std::string(argv[1]);
    std::string output_file = std::string(argv[3]);

    std::cerr<<"Computing the FM-index from the input BCR BWT"<<std::endl;
    fm_index fmi(input_file);

    std::cerr<<"decompressing the first "<<n_seqs<<" sequences "<<std::endl;
    std::string seq;
    o_file_stream<uint8_t> o_buff(output_file, 1024*1024, std::ios::out);

    for(long i=0;i<n_seqs;i++){
        seq.clear();
        auto res = fmi.lf(i);
        size_t next_pos = res.second;
        uint8_t sym = res.first;
        while(sym!=fmi.get_dummy()){
            seq.push_back((char)sym);
            res = fmi.lf(next_pos);
            next_pos = res.second;
            sym = res.first;
        }
        std::reverse(seq.begin(), seq.end());
        seq.push_back((char)fmi.get_dummy());
        for(char j : seq){
            o_buff.push_back(j);
        }
    }
    o_buff.close();
}